import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <meta property="og:image" content="<generated>" />
<meta property="og:image:type" content="<generated>" />
<meta property="og:image:width" content="<generated>" />
<meta property="og:image:height" content="<generated>" />
<meta property="og:site_name" content="Link preview site name" />
<meta property="og:title" content="Link preview title" />
<meta property="og:description" content="Link preview description" />
<meta property="twitter:image" content="Twitter link preview image URL"></meta>
<meta property="twitter:card" content="summary_large_image"></meta>
<meta property="twitter:description" content="Twitter link preview description"></meta>
<meta property="twitter:title" content="Twitter link preview title"></meta>
<meta property="og:url" content="https://wwww.danceclash.vercel.app"></meta>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
