import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <meta property="og:image" content="<generated>" />
<meta property="og:image:type" content="<generated>" />
<meta property="og:image:width" content="<generated>" />
<meta property="og:image:height" content="<generated>" />
<meta property="og:site_name" content="https://www.danceclash.vercel.app" />
<meta property="og:title" content="Dance Clash" />
<meta property="og:description" content="Challange Your Friends To A Dance Battle" />
<meta property="twitter:image" content=""></meta>
<meta property="twitter:card" content="summary_large_image"></meta>
<meta property="twitter:description" content="Challange Your Friends To A Dance Battle"></meta>
<meta property="twitter:title" content="Dance Clash"></meta>
<meta property="og:url" content="https://www.danceclash.vercel.app"></meta>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
